# Latihan Penggabungan Data Penilaian 2018 dan 2019

Nama : Diah Ayu Puspasari

NIM : 0110223052

Rombel : Data Engineering 02

In [ ]:
# import library pandas dan yang lain
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# menghubungkan dengan google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# mengimpoert file dari google drive
path = '/content/drive/MyDrive/datasciece/dataset'

In [ ]:
# membaca file csv penilaian 2019
data2019 = pd.read_csv(path + '/karyawan-penilaian2019.csv')
data2019

    id_karyawan           nama_pegawai  Penilaian 2019
0      10010101            Indra Hasan              87
1      10010102      Fachriadi Abidzar              84
2      10010103          Hilmy Ghozali              80
3      10010105      Khakim Adriansyah              90
4      10010106           Henry Rosyid              79
5      10010107           Misna Oktina              78
6      10010108           Lukman Hakim              92
7      10010109     Dwi Primardiansyah              99
8      10010110          Ahmad Firdaus              80
9      10010111      Bachtiar Hermawan              75
10     10010113       La Ode Kurniawan              93
11     10010114               Maisarah              97
12     10010116  Abdul Rozak El Farisi             100
13     10010117          Amalia Rizqia              98
14     10010118            Dian Rahmah              77
15     10010119          Reza Maryanto              88
16     10010120      Zaki Adityawijaya              78

In [ ]:
# membaca file csv penilaian 2018
data2018 = pd.read_csv(path + '/karyawan-penilaian2018.csv')
data2018

          ID          Nama Pegawai  Penilaian 2018
0   10010101           Indra Hasan              79
1   10010102     Fachriadi Abidzar              83
2   10010103         Hilmy Ghozali              75
3   10010104  Nugroho Aldi Saputra              64
4   10010105     Khakim Adriansyah              90
5   10010106          Henry Rosyid              89
6   10010107          Misna Oktina              84
7   10010108          Lukman Hakim              93
8   10010109    Dwi Primardiansyah              98
9   10010110         Ahmad Firdaus              78
10  10010111     Bachtiar Hermawan              73
11  10010112          Luthfiansyah              66
12  10010113      La Ode Kurniawan              86
13  10010114              Maisarah              89
14  10010115        April Rusmanto              68

In [ ]:
# Rename kolom dulu biar seragam
data2018 = data2018.rename(columns={
    'ID': 'id_karyawan',
    'Nama Pegawai': 'nama_pegawai'
})

In [ ]:
# Gabungkan data dengan outer join berdasarkan id_karyawan dan nama_pegawai
data_gabungan = pd.merge(data2018, data2019, on=['id_karyawan', 'nama_pegawai'], how='outer')
data_gabungan

    id_karyawan           nama_pegawai  Penilaian 2018  Penilaian 2019
0      10010101            Indra Hasan            79.0            87.0
1      10010102      Fachriadi Abidzar            83.0            84.0
2      10010103          Hilmy Ghozali            75.0            80.0
3      10010104   Nugroho Aldi Saputra            64.0             NaN
4      10010105      Khakim Adriansyah            90.0            90.0
5      10010106           Henry Rosyid            89.0            79.0
6      10010107           Misna Oktina            84.0            78.0
7      10010108           Lukman Hakim            93.0            92.0
8      10010109     Dwi Primardiansyah            98.0            99.0
9      10010110          Ahmad Firdaus            78.0            80.0
10     10010111      Bachtiar Hermawan            73.0            75.0
11     10010112           Luthfiansyah            66.0             NaN
12     10010113       La Ode Kurniawan            86.0            93.0
13     10010114               Maisarah            89.0            97.0
14     10010115         April Rusmanto            68.0             NaN
15     10010116  Abdul Rozak El Farisi             NaN           100.0
16     10010117          Amalia Rizqia             NaN            98.0
17     10010118            Dian Rahmah             NaN            77.0
18     10010119          Reza Maryanto             NaN            88.0
19     10010120      Zaki Adityawijaya             NaN            78.0

## Siapa saja karyawan yang performanya naik dari 2018 ke 2019?

In [ ]:
# Filter hanya yang performanya naik
performa_naik = data_gabungan[data_gabungan['Penilaian 2019'] > data_gabungan['Penilaian 2018']]

performa_naik

    id_karyawan        nama_pegawai  Penilaian 2018  Penilaian 2019
0      10010101         Indra Hasan            79.0            87.0
1      10010102   Fachriadi Abidzar            83.0            84.0
2      10010103       Hilmy Ghozali            75.0            80.0
8      10010109  Dwi Primardiansyah            98.0            99.0
9      10010110       Ahmad Firdaus            78.0            80.0
10     10010111   Bachtiar Hermawan            73.0            75.0
12     10010113    La Ode Kurniawan            86.0            93.0
13     10010114            Maisarah            89.0            97.0

In [ ]:
# membuat kolom baru untuk Keterangan karyawan yang baru dan keluar
def status_karyawan(row):
    if pd.isnull(row['Penilaian 2018']) and not pd.isnull(row['Penilaian 2019']):
        return 'Karyawan Baru'
    elif not pd.isnull(row['Penilaian 2018']) and pd.isnull(row['Penilaian 2019']):
        return 'Karyawan Keluar'
    elif not pd.isnull(row['Penilaian 2018']) and not pd.isnull(row['Penilaian 2019']):
        return 'Tetap'
    else:
        return 'Tidak Ada Data'

data_gabungan['Keterangan'] = data_gabungan.apply(status_karyawan, axis=1)
data_gabungan

,id_karyawan,nama_pegawai,Penilaian 2018,Penilaian 2019,Keterangan
0,10010101,Indra Hasan,79.0,87.0,Tetap
1,10010102,Fachriadi Abidzar,83.0,84.0,Tetap
2,10010103,Hilmy Ghozali,75.0,80.0,Tetap
3,10010104,Nugroho Aldi Saputra,64.0,NaN,Karyawan Keluar
4,10010105,Khakim Adriansyah,90.0,90.0,Tetap
5,10010106,Henry Rosyid,89.0,79.0,Tetap
6,10010107,Misna Oktina,84.0,78.0,Tetap
7,10010108,Lukman Hakim,93.0,92.0,Tetap
8,10010109,Dwi Primardiansyah,98.0,99.0,Tetap
9,10010110,Ahmad Firdaus,78.0,80.0,Tetap
10,10010111,Bachtiar Hermawan,73.0,75.0,Tetap
11,10010112,Luthfiansyah,66.0,NaN,Karyawan Keluar
12,10010113,La Ode Kurniawan,86.0,93.0,Tetap
13,10010114,Maisarah,89.0,97.0,Tetap
14,10010115,April Rusmanto,68.0,NaN,Karyawan Keluar
15,10010116,Abdul Rozak El Farisi,NaN,100.0,Karyawan Baru
16,10010117,Amalia Rizqia,NaN,98.0,Karyawan Baru
17,10010118,Dian Rahmah,NaN,77.0,Karyawan Baru
18,10010119,Reza Maryanto,NaN,88.0,Karyawan Baru
19,10010120,Zaki Adityawijaya,NaN,78.0,Karyawan Baru

## Siapa saja karyawan baru di 2019?

In [ ]:
# menampilkan data karyawan baru
karyawan_baru = data_gabungan[data_gabungan['Keterangan'] == 'Karyawan Baru']
karyawan_baru

,id_karyawan,nama_pegawai,Penilaian 2018,Penilaian 2019,Keterangan
15,10010116,Abdul Rozak El Farisi,NaN,100.0,Karyawan Baru
16,10010117,Amalia Rizqia,NaN,98.0,Karyawan Baru
17,10010118,Dian Rahmah,NaN,77.0,Karyawan Baru
18,10010119,Reza Maryanto,NaN,88.0,Karyawan Baru
19,10010120,Zaki Adityawijaya,NaN,78.0,Karyawan Baru

## Siapa saja yang keluar di 2019?

In [ ]:
# menampilkan data karyawan yang keluar
karyawan_keluar = data_gabungan[data_gabungan['Keterangan'] == 'Karyawan Keluar']
karyawan_keluar

,id_karyawan,nama_pegawai,Penilaian 2018,Penilaian 2019,Keterangan
3,10010104,Nugroho Aldi Saputra,64.0,NaN,Karyawan Keluar
11,10010112,Luthfiansyah,66.0,NaN,Karyawan Keluar
14,10010115,April Rusmanto,68.0,NaN,Karyawan Keluar

## Table gabungannya di simpan sebagai file CSV

In [ ]:
data_gabungan.to_csv("evaluasi_karyawan.csv", index=False)

# Latihan Penggabungan Data Karyawan 1 dan 2

In [ ]:
# membaca file csv karyawan 1
karyawan1 = pd.read_csv(path + '/karyawan1.csv')
karyawan1

,ID,Nama Pegawai,Tempat Lahir,Tanggal Lahir,Jenis Kelamin,Kota Tempat Tinggal,No HP,Jam Kerja,Berat
0,10010104,Nugroho Aldi Saputra,Jakarta,11-06-1982,L,Depok,NaN,8,78.0
1,10010106,Henry Rosyid,Jakarta,13-07-1971,L,Bogor,8.991111e+10,8,52.0
2,10010119,Reza Maryanto,Sukabumi,31-01-1981,L,Depok,NaN,8,62.5
3,10010108,Lukman Hakim,Majalengka,14-07-1988,L,Bogor,8.122222e+10,8,82.5
4,10010109,Dwi Primardiansyah,Pekalongan,15-05-1983,L,Bogor,8.883333e+10,9,52.0
5,10010107,Misna Oktina,Jakarta,14-04-1971,P,Depok,NaN,8,97.0
6,10010111,Bachtiar Hermawan,Jakarta,23-06-1963,L,Jakarta,8.151112e+10,9,89.0
7,10010112,Luthfiansyah,Majalengka,24-08-1989,L,Depok,8.582223e+10,8,69.0
8,10010120,Zaki Adityawijaya,Jakarta,31-08-1987,L,Depok,8.125556e+10,9,66.0
9,10010110,Ahmad Firdaus,Pekalongan,17-08-1980,L,Jakarta,NaN,9,83.0

In [ ]:
# membaca file csv karyawan 2
karyawan2 = pd.read_csv(path + '/karyawan2.csv')
karyawan2

,ID,Nama Pegawai,Tempat Lahir,Tanggal Lahir,Jenis Kelamin,Kota Tempat Tinggal,No HP,Jam Kerja,Berat
0,10010117,Amalia Rizqia,Jakarta,29-07-1983,P,Jakarta,8.883334e+10,8,70.0
1,10010103,Hilmy Ghozali,Jakarta,06-11-1972,L,Bogor,NaN,9,47.5
2,10010113,La Ode Kurniawan,Muna,25-05-1980,L,Bogor,8.123334e+10,8,77.0
3,10010105,Khakim Adriansyah,Ciamis,12-03-1987,L,Bogor,8.132222e+10,8,73.0
4,10010115,April Rusmanto,Cilacap,27-12-1977,L,Jakarta,8.121112e+10,9,56.0
5,10010101,Indra Hasan,Bogor,01-01-1971,L,Bogor,8.121111e+10,9,45.0
6,10010102,Fachriadi Abidzar,Depok,01-09-1959,L,Jakarta,8.561111e+10,8,73.0
7,10010114,Maisarah,Cilacap,26-09-1965,P,Depok,8.154445e+10,8,56.0
8,10010116,Abdul Rozak El Farisi,Jakarta,29-05-1988,L,Depok,8.562223e+10,9,61.0
9,10010118,Dian Rahmah,Cilacap,30-08-1989,P,Jakarta,8.134445e+10,9,65.0

## Gabungkan kedua file tersebut

In [ ]:
# menggabungkan data frame karyawan 1 dan karyawan 2 dengan index 0 - 19
data_karyawan = pd.concat([karyawan1, karyawan2], ignore_index=True)
data_karyawan

,ID,Nama Pegawai,Tempat Lahir,Tanggal Lahir,Jenis Kelamin,Kota Tempat Tinggal,No HP,Jam Kerja,Berat
0,10010104,Nugroho Aldi Saputra,Jakarta,11-06-1982,L,Depok,NaN,8,78.0
1,10010106,Henry Rosyid,Jakarta,13-07-1971,L,Bogor,8.991111e+10,8,52.0
2,10010119,Reza Maryanto,Sukabumi,31-01-1981,L,Depok,NaN,8,62.5
3,10010108,Lukman Hakim,Majalengka,14-07-1988,L,Bogor,8.122222e+10,8,82.5
4,10010109,Dwi Primardiansyah,Pekalongan,15-05-1983,L,Bogor,8.883333e+10,9,52.0
5,10010107,Misna Oktina,Jakarta,14-04-1971,P,Depok,NaN,8,97.0
6,10010111,Bachtiar Hermawan,Jakarta,23-06-1963,L,Jakarta,8.151112e+10,9,89.0
7,10010112,Luthfiansyah,Majalengka,24-08-1989,L,Depok,8.582223e+10,8,69.0
8,10010120,Zaki Adityawijaya,Jakarta,31-08-1987,L,Depok,8.125556e+10,9,66.0
9,10010110,Ahmad Firdaus,Pekalongan,17-08-1980,L,Jakarta,NaN,9,83.0
10,10010117,Amalia Rizqia,Jakarta,29-07-1983,P,Jakarta,8.883334e+10,8,70.0
11,10010103,Hilmy Ghozali,Jakarta,06-11-1972,L,Bogor,NaN,9,47.5
12,10010113,La Ode Kurniawan,Muna,25-05-1980,L,Bogor,8.123334e+10,8,77.0
13,10010105,Khakim Adriansyah,Ciamis,12-03-1987,L,Bogor,8.132222e+10,8,73.0
14,10010115,April Rusmanto,Cilacap,27-12-1977,L,Jakarta,8.121112e+10,9,56.0
15,10010101,Indra Hasan,Bogor,01-01-1971,L,Bogor,8.121111e+10,9,45.0
16,10010102,Fachriadi Abidzar,Depok,01-09-1959,L,Jakarta,8.561111e+10,8,73.0
17,10010114,Maisarah,Cilacap,26-09-1965,P,Depok,8.154445e+10,8,56.0
18,10010116,Abdul Rozak El Farisi,Jakarta,29-05-1988,L,Depok,8.562223e+10,9,61.0
19,10010118,Dian Rahmah,Cilacap,30-08-1989,P,Jakarta,8.134445e+10,9,65.0

## Simpan sebagai data.karyawan.csv

In [ ]:
# menyimpan data karyawan sebagai csv
data_karyawan.to_csv("data_karyawan.csv", index=False)

## Gabungkan data karyawan dengan nilai evaluasinya, Simpan sebagai data_evaluasi_karyawan.csv

In [ ]:
# merename kolom ID menjadi id_karyawan pada data_karyawan
data_karyawan = data_karyawan.rename(columns={'ID': 'id_karyawan'})
data_karyawan

,id_karyawan,Nama Pegawai,Tempat Lahir,Tanggal Lahir,Jenis Kelamin,Kota Tempat Tinggal,No HP,Jam Kerja,Berat
0,10010104,Nugroho Aldi Saputra,Jakarta,11-06-1982,L,Depok,NaN,8,78.0
1,10010106,Henry Rosyid,Jakarta,13-07-1971,L,Bogor,8.991111e+10,8,52.0
2,10010119,Reza Maryanto,Sukabumi,31-01-1981,L,Depok,NaN,8,62.5
3,10010108,Lukman Hakim,Majalengka,14-07-1988,L,Bogor,8.122222e+10,8,82.5
4,10010109,Dwi Primardiansyah,Pekalongan,15-05-1983,L,Bogor,8.883333e+10,9,52.0
5,10010107,Misna Oktina,Jakarta,14-04-1971,P,Depok,NaN,8,97.0
6,10010111,Bachtiar Hermawan,Jakarta,23-06-1963,L,Jakarta,8.151112e+10,9,89.0
7,10010112,Luthfiansyah,Majalengka,24-08-1989,L,Depok,8.582223e+10,8,69.0
8,10010120,Zaki Adityawijaya,Jakarta,31-08-1987,L,Depok,8.125556e+10,9,66.0
9,10010110,Ahmad Firdaus,Pekalongan,17-08-1980,L,Jakarta,NaN,9,83.0
10,10010117,Amalia Rizqia,Jakarta,29-07-1983,P,Jakarta,8.883334e+10,8,70.0
11,10010103,Hilmy Ghozali,Jakarta,06-11-1972,L,Bogor,NaN,9,47.5
12,10010113,La Ode Kurniawan,Muna,25-05-1980,L,Bogor,8.123334e+10,8,77.0
13,10010105,Khakim Adriansyah,Ciamis,12-03-1987,L,Bogor,8.132222e+10,8,73.0
14,10010115,April Rusmanto,Cilacap,27-12-1977,L,Jakarta,8.121112e+10,9,56.0
15,10010101,Indra Hasan,Bogor,01-01-1971,L,Bogor,8.121111e+10,9,45.0
16,10010102,Fachriadi Abidzar,Depok,01-09-1959,L,Jakarta,8.561111e+10,8,73.0
17,10010114,Maisarah,Cilacap,26-09-1965,P,Depok,8.154445e+10,8,56.0
18,10010116,Abdul Rozak El Farisi,Jakarta,29-05-1988,L,Depok,8.562223e+10,9,61.0
19,10010118,Dian Rahmah,Cilacap,30-08-1989,P,Jakarta,8.134445e+10,9,65.0

In [ ]:
data_evaluasi = pd.merge(data_karyawan, data_gabungan, on='id_karyawan', how='outer')
data_evaluasi

,id_karyawan,Nama Pegawai,Tempat Lahir,Tanggal Lahir,Jenis Kelamin,Kota Tempat Tinggal,No HP,Jam Kerja,Berat,nama_pegawai,Penilaian 2018,Penilaian 2019,Keterangan
0,10010101,Indra Hasan,Bogor,01-01-1971,L,Bogor,8.121111e+10,9,45.0,Indra Hasan,79.0,87.0,Tetap
1,10010102,Fachriadi Abidzar,Depok,01-09-1959,L,Jakarta,8.561111e+10,8,73.0,Fachriadi Abidzar,83.0,84.0,Tetap
2,10010103,Hilmy Ghozali,Jakarta,06-11-1972,L,Bogor,NaN,9,47.5,Hilmy Ghozali,75.0,80.0,Tetap
3,10010104,Nugroho Aldi Saputra,Jakarta,11-06-1982,L,Depok,NaN,8,78.0,Nugroho Aldi Saputra,64.0,NaN,Karyawan Keluar
4,10010105,Khakim Adriansyah,Ciamis,12-03-1987,L,Bogor,8.132222e+10,8,73.0,Khakim Adriansyah,90.0,90.0,Tetap
5,10010106,Henry Rosyid,Jakarta,13-07-1971,L,Bogor,8.991111e+10,8,52.0,Henry Rosyid,89.0,79.0,Tetap
6,10010107,Misna Oktina,Jakarta,14-04-1971,P,Depok,NaN,8,97.0,Misna Oktina,84.0,78.0,Tetap
7,10010108,Lukman Hakim,Majalengka,14-07-1988,L,Bogor,8.122222e+10,8,82.5,Lukman Hakim,93.0,92.0,Tetap
8,10010109,Dwi Primardiansyah,Pekalongan,15-05-1983,L,Bogor,8.883333e+10,9,52.0,Dwi Primardiansyah,98.0,99.0,Tetap
9,10010110,Ahmad Firdaus,Pekalongan,17-08-1980,L,Jakarta,NaN,9,83.0,Ahmad Firdaus,78.0,80.0,Tetap
10,10010111,Bachtiar Hermawan,Jakarta,23-06-1963,L,Jakarta,8.151112e+10,9,89.0,Bachtiar Hermawan,73.0,75.0,Tetap
11,10010112,Luthfiansyah,Majalengka,24-08-1989,L,Depok,8.582223e+10,8,69.0,Luthfiansyah,66.0,NaN,Karyawan Keluar
12,10010113,La Ode Kurniawan,Muna,25-05-1980,L,Bogor,8.123334e+10,8,77.0,La Ode Kurniawan,86.0,93.0,Tetap
13,10010114,Maisarah,Cilacap,26-09-1965,P,Depok,8.154445e+10,8,56.0,Maisarah,89.0,97.0,Tetap
14,10010115,April Rusmanto,Cilacap,27-12-1977,L,Jakarta,8.121112e+10,9,56.0,April Rusmanto,68.0,NaN,Karyawan Keluar
15,10010116,Abdul Rozak El Farisi,Jakarta,29-05-1988,L,Depok,8.562223e+10,9,61.0,Abdul Rozak El Farisi,NaN,100.0,Karyawan Baru
16,10010117,Amalia Rizqia,Jakarta,29-07-1983,P,Jakarta,8.883334e+10,8,70.0,Amalia Rizqia,NaN,98.0,Karyawan Baru
17,10010118,Dian Rahmah,Cilacap,30-08-1989,P,Jakarta,8.134445e+10,9,65.0,Dian Rahmah,NaN,77.0,Karyawan Baru
18,10010119,Reza Maryanto,Sukabumi,31-01-1981,L,Depok,NaN,8,62.5,Reza Maryanto,NaN,88.0,Karyawan Baru
19,10010120,Zaki Adityawijaya,Jakarta,31-08-1987,L,Depok,8.125556e+10,9,66.0,Zaki Adityawijaya,NaN,78.0,Karyawan Baru

In [ ]:
# menyimpan data evaluasi karyawan sebagai csv
data_evaluasi.to_csv("data_evaluasi_karyawan.csv", index=False)

# Latihan Cleaning Data

In [ ]:
# membaca file csv dirty data
dirty_data = pd.read_csv(path + '/dirtydata.csv')
dirty_data

,ID,Nama Pegawai,Tempat Lahir,Tanggal Lahir,Jenis Kelamin,Kota Tempat Tinggal,No HP,Jam Kerja,Berat
0,10010104,Nugroho Aldi Saputra,Jakarta,11-06-1982,Pria,Depok,NaN,8,78
1,10010106,Henry Rosyid,Jakarta,13-07-1971,L,Bogor,8.991111e+10,8 AM,52
2,10010107,Misna Oktina,Jakarta,14-04-1971,NaN,NaN,NaN,NaN,74
3,10010119,Reza Maryanto,Sukabumi,31-01-1981,L,Depok,NaN,8:00,62.5
4,10010108,Lukman Hakim,Majalengka,14-07-1988,L,Bogor,8.122222e+10,8,"82,5"
5,10010109,Dwi Primardiansyah,Pekalongan,15-05-1983,L,Bogor,8.883333e+10,9,52
6,10010107,Misna Oktina,Jakarta,14-04-1971,Wanita,Depok,NaN,8:00,97
7,10010111,Bachtiar Hermawan,Jakarta,23-06-1963,Laki-Laki,Jakarta,8.151112e+10,9,890
8,10010112,Luthfiansyah,Majalengka,24-08-1989,L,Depok,8.582223e+10,8,69
9,10010120,Zaki Adityawijaya,Jakarta,31-08-1987,L,Depok,8.125556e+10,9,66
10,10010110,Ahmad Firdaus,Pekalongan,17-08-1980,L,Jakarta,NaN,9,83
11,10010117,Amalia Rizqia,Jakarta,29-07-1983,P,Jakarta,8.883334e+10,8,70
12,10010103,Hilmy Ghozali,Jakarta,06-11-1972,Laki-Laki,Bogor,NaN,9:00,47.5
13,10010113,La Ode Kurniawan,Muna,25-05-1980,L,Bogor,8.123334e+10,8,77
14,10010105,Khakim Adriansyah,Ciamis,12-03-1987,L,Bogor,8.132222e+10,8 WIB,73
15,10010115,April Rusmanto,Cilacap,27-12-1977,L,Jakarta,8.121112e+10,9,56
16,10010101,Indra Hasan,Bogor,01-01-1971,Pria,Bogor,8.121111e+10,9,45
17,10010102,Fachriadi Abidzar,Depok,01-09-1959,L,Jakarta,8.561111e+10,8:00,73
18,10010114,Maisarah,Cilacap,26-09-1965,Perempuan,Depok,8.154445e+10,88,56 kg
19,10010116,Abdul Rozak El Farisi,Jakarta,29-05-1988,L,Depok,8.562223e+10,9,61
20,10010118,Dian Rahmah,Cilacap,30-08-1989,P,Jakarta,8.134445e+10,9,65

In [ ]:
dirty_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   21 non-null     int64
 1   Nama Pegawai         21 non-null     object
 2   Tempat Lahir         21 non-null     object
 3   Tanggal Lahir        21 non-null     object
 4   Jenis Kelamin        20 non-null     object
 5   Kota Tempat Tinggal  20 non-null     object
 6   No HP                15 non-null     float64
 7   Jam Kerja            20 non-null     object
 8   Berat                21 non-null     object
dtypes: float64(1), int64(1), object(7)
memory usage: 1.6+ KB

In [ ]:
# mengubah tipe data (transformasi) Tanggal Lahir ke datetime
dirty_data['Tanggal Lahir'].apply(pd.to_datetime)

dirty_data

<ipython-input-45-2f988054a293>:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  dirty_data['Tanggal Lahir'].apply(pd.to_datetime)

,ID,Nama Pegawai,Tempat Lahir,Tanggal Lahir,Jenis Kelamin,Kota Tempat Tinggal,No HP,Jam Kerja,Berat
0,10010104,Nugroho Aldi Saputra,Jakarta,11-06-1982,Pria,Depok,NaN,8,78
1,10010106,Henry Rosyid,Jakarta,13-07-1971,L,Bogor,8.991111e+10,8 AM,52
2,10010107,Misna Oktina,Jakarta,14-04-1971,NaN,NaN,NaN,NaN,74
3,10010119,Reza Maryanto,Sukabumi,31-01-1981,L,Depok,NaN,8:00,62.5
4,10010108,Lukman Hakim,Majalengka,14-07-1988,L,Bogor,8.122222e+10,8,"82,5"
5,10010109,Dwi Primardiansyah,Pekalongan,15-05-1983,L,Bogor,8.883333e+10,9,52
6,10010107,Misna Oktina,Jakarta,14-04-1971,Wanita,Depok,NaN,8:00,97
7,10010111,Bachtiar Hermawan,Jakarta,23-06-1963,Laki-Laki,Jakarta,8.151112e+10,9,890
8,10010112,Luthfiansyah,Majalengka,24-08-1989,L,Depok,8.582223e+10,8,69
9,10010120,Zaki Adityawijaya,Jakarta,31-08-1987,L,Depok,8.125556e+10,9,66
10,10010110,Ahmad Firdaus,Pekalongan,17-08-1980,L,Jakarta,NaN,9,83
11,10010117,Amalia Rizqia,Jakarta,29-07-1983,P,Jakarta,8.883334e+10,8,70
12,10010103,Hilmy Ghozali,Jakarta,06-11-1972,Laki-Laki,Bogor,NaN,9:00,47.5
13,10010113,La Ode Kurniawan,Muna,25-05-1980,L,Bogor,8.123334e+10,8,77
14,10010105,Khakim Adriansyah,Ciamis,12-03-1987,L,Bogor,8.132222e+10,8 WIB,73
15,10010115,April Rusmanto,Cilacap,27-12-1977,L,Jakarta,8.121112e+10,9,56
16,10010101,Indra Hasan,Bogor,01-01-1971,Pria,Bogor,8.121111e+10,9,45
17,10010102,Fachriadi Abidzar,Depok,01-09-1959,L,Jakarta,8.561111e+10,8:00,73
18,10010114,Maisarah,Cilacap,26-09-1965,Perempuan,Depok,8.154445e+10,88,56 kg
19,10010116,Abdul Rozak El Farisi,Jakarta,29-05-1988,L,Depok,8.562223e+10,9,61
20,10010118,Dian Rahmah,Cilacap,30-08-1989,P,Jakarta,8.134445e+10,9,65

In [ ]:
# mengubah tipe data (transformasi) menggunakan astype
dirty_data.astype({'ID':int, 'Tempat Lahir':'category', 'No HP': str})

,ID,Nama Pegawai,Tempat Lahir,Tanggal Lahir,Jenis Kelamin,Kota Tempat Tinggal,No HP,Jam Kerja,Berat
0,10010104,Nugroho Aldi Saputra,Jakarta,11-06-1982,Pria,Depok,nan,8,78
1,10010106,Henry Rosyid,Jakarta,13-07-1971,L,Bogor,89911114444.0,8 AM,52
2,10010107,Misna Oktina,Jakarta,14-04-1971,NaN,NaN,nan,NaN,74
3,10010119,Reza Maryanto,Sukabumi,31-01-1981,L,Depok,nan,8:00,62.5
4,10010108,Lukman Hakim,Majalengka,14-07-1988,L,Bogor,81222224444.0,8,"82,5"
5,10010109,Dwi Primardiansyah,Pekalongan,15-05-1983,L,Bogor,88833334444.0,9,52
6,10010107,Misna Oktina,Jakarta,14-04-1971,Wanita,Depok,nan,8:00,97
7,10010111,Bachtiar Hermawan,Jakarta,23-06-1963,Laki-Laki,Jakarta,81511115555.0,9,890
8,10010112,Luthfiansyah,Majalengka,24-08-1989,L,Depok,85822225555.0,8,69
9,10010120,Zaki Adityawijaya,Jakarta,31-08-1987,L,Depok,81255556666.0,9,66
10,10010110,Ahmad Firdaus,Pekalongan,17-08-1980,L,Jakarta,nan,9,83
11,10010117,Amalia Rizqia,Jakarta,29-07-1983,P,Jakarta,88833336666.0,8,70
12,10010103,Hilmy Ghozali,Jakarta,06-11-1972,Laki-Laki,Bogor,nan,9:00,47.5
13,10010113,La Ode Kurniawan,Muna,25-05-1980,L,Bogor,81233335555.0,8,77
14,10010105,Khakim Adriansyah,Ciamis,12-03-1987,L,Bogor,81322223333.0,8 WIB,73
15,10010115,April Rusmanto,Cilacap,27-12-1977,L,Jakarta,81211116666.0,9,56
16,10010101,Indra Hasan,Bogor,01-01-1971,Pria,Bogor,81211112222.0,9,45
17,10010102,Fachriadi Abidzar,Depok,01-09-1959,L,Jakarta,85611113333.0,8:00,73
18,10010114,Maisarah,Cilacap,26-09-1965,Perempuan,Depok,81544445555.0,88,56 kg
19,10010116,Abdul Rozak El Farisi,Jakarta,29-05-1988,L,Depok,85622226666.0,9,61
20,10010118,Dian Rahmah,Cilacap,30-08-1989,P,Jakarta,81344446666.0,9,65

In [ ]:
dirty_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   21 non-null     int64
 1   Nama Pegawai         21 non-null     object
 2   Tempat Lahir         21 non-null     object
 3   Tanggal Lahir        21 non-null     object
 4   Jenis Kelamin        20 non-null     object
 5   Kota Tempat Tinggal  20 non-null     object
 6   No HP                15 non-null     float64
 7   Jam Kerja            20 non-null     object
 8   Berat                21 non-null     object
dtypes: float64(1), int64(1), object(7)
memory usage: 1.6+ KB

In [ ]:
dirty_data['Jenis Kelamin'].unique()

array(['Pria', 'L', nan, 'Wanita', 'Laki-Laki', 'P', 'Perempuan'],
      dtype=object)

In [ ]:
dirty_data['ID'].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
Name: ID, dtype: bool

In [ ]:
dirty_data['ID'].duplicated().sum()

np.int64(1)

Latihan Tambahkan data pribadi dan boleh Dummy

Opsional data fiffa nanti ada pengumpulannya